version: '3'

services:
  mongo:
    container_name: music_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network
  app:
    container_name: music_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - network

networks:
  network:
    driver: bridge