version: '3'

services:
  mongo:
    container_name: music_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network
  app:
    container_name: music_app
    privileged: true
    #volumes:
      # for develop mode
      #- ./public/javascripts/master.js:/app/public/javascripts/master.js
      #- ./public/javascripts/player.js:/app/public/javascripts/player.js
      #- ./views:/app/views
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - network

networks:
  network:
    driver: bridge